<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
      <PackageReference Include="MediatR" Version="12.4.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
      <PackageReference Include="MongoDB.EntityFrameworkCore" Version="8.2.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\API\Heyer.Storage.API.Client\Heyer.Storage.API.Client.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Heyer.BuildingBlocks.Infrastructure\Heyer.BuildingBlocks.Infrastructure.csproj" />
      <ProjectReference Include="..\Heyer.Modules.Candidates.Application\Heyer.Modules.Candidates.Application.csproj" />
      <ProjectReference Include="..\Heyer.Modules.Candidates.Domain\Heyer.Modules.Candidates.Domain.csproj" />
    </ItemGroup>

</Project>
