<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Heyer.Modules.Hiring.Application\Heyer.Modules.Hiring.Application.csproj"/>
    <ProjectReference Include="..\Heyer.Modules.Hiring.Domain\Heyer.Modules.Hiring.Domain.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="3.16.0"/>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0"/>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Heyer.API.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Heyer.Modules.Hiring.Infrastructure.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
