<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults"/>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
    <PackageReference Include="Npgsql"/>
    <PackageReference Include="NUnit"/>
    <PackageReference Include="Serilog.Extensions.Logging"/>
    <PackageReference Include="Shouldly"/>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt"/>
    <PackageReference Include="Testcontainers.MongoDb"/>
    <PackageReference Include="Testcontainers.PostgreSql"/>
    <PackageReference Include="Testcontainers.SqlEdge"/>
  </ItemGroup>

  <ItemGroup>
    <None Update="signing.cer">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
