<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0"/>
    <PackageReference Include="FluentAssertions" Version="6.12.2"/>
    <PackageReference Include="FluentResults.Extensions.FluentAssertions" Version="2.1.2"/>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.0"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0"/>
    <PackageReference Include="NSubstitute" Version="5.3.0"/>
    <PackageReference Include="NUnit" Version="4.2.2"/>
    <PackageReference Include="NUnit.Analyzers" Version="3.9.0"/>
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0"/>
    <PackageReference Include="Testcontainers.MongoDb" Version="4.1.0"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\API\Heyer.Storage.API\Heyer.Storage.API.csproj"/>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\Heyer.BuildingBlocks.Tests\Heyer.BuildingBlocks.Tests.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Update="Utils\TestFiles\test-file.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Utils\TestFiles\test-file.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
