<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector"/>
    <PackageReference Include="Shouldly"/>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="NSubstitute"/>
    <PackageReference Include="NUnit"/>
    <PackageReference Include="NUnit.Analyzers"/>
    <PackageReference Include="NUnit3TestAdapter"/>
    <PackageReference Include="Testcontainers.MongoDb"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\API\Heyer.Storage.API\Heyer.Storage.API.csproj"/>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\Heyer.BuildingBlocks.Json\Heyer.BuildingBlocks.Json.csproj"/>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\Heyer.BuildingBlocks.Tests\Heyer.BuildingBlocks.Tests.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Update="Utils\TestFiles\test-file.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Utils\TestFiles\test-file.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
