<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Heyer.Modules.JobBoard.Application.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus"/>
    <PackageReference Include="coverlet.collector"/>
    <PackageReference Include="Shouldly"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="NSubstitute"/>
    <PackageReference Include="NUnit"/>
    <PackageReference Include="NUnit.Analyzers"/>
    <PackageReference Include="NUnit3TestAdapter"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\Heyer.BuildingBlocks.Application\Heyer.BuildingBlocks.Application.csproj"/>
    <ProjectReference Include="..\..\..\src\Modules\JobBoard\Heyer.Modules.JobBoard.Application\Heyer.Modules.JobBoard.Application.csproj"/>
    <ProjectReference Include="..\..\..\src\Modules\JobBoard\Heyer.Modules.JobBoard.Domain\Heyer.Modules.JobBoard.Domain.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="JobOffers\"/>
  </ItemGroup>

</Project>
