<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="**/*.sql"/>
  </ItemGroup>

  <ItemGroup> <!-- this is sketchy but no better idea at this moment -->
    <Content Include="..\..\API\Heyer.API\appsettings.json">
      <Link>appsettings.api.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\API\Heyer.Storage.API\appsettings.json">
      <Link>appsettings.storage.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cocona"/>
    <PackageReference Include="dbup-postgresql"/>
    <PackageReference Include="MediatR"/>
    <PackageReference Include="Serilog"/>
    <PackageReference Include="Serilog.AspNetCore"/>
    <PackageReference Include="Serilog.Sinks.Console"/>
  </ItemGroup>
</Project>
