<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="3.16.0"/>
    <PackageReference Include="FluentValidation" Version="11.11.0"/>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.17"/>
    <PackageReference Include="Hangfire" Version="1.8.17"/>
    <PackageReference Include="MediatR" Version="12.4.1"/>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0"/>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3"/>
    <PackageReference Include="Serilog" Version="4.2.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Heyer.BuildingBlocks.Application\Heyer.BuildingBlocks.Application.csproj"/>
    <ProjectReference Include="..\Heyer.BuildingBlocks.Domain\Heyer.BuildingBlocks.Domain.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Heyer.BuildingBlocks.Infrastructure.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
