<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults"/>
    <PackageReference Include="FluentValidation"/>
    <PackageReference Include="Hangfire.AspNetCore"/>
    <PackageReference Include="Hangfire"/>
    <PackageReference Include="Hangfire.PostgreSql"/>
    <PackageReference Include="MediatR"/>
    <PackageReference Include="Microsoft.Data.SqlClient"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    <PackageReference Include="Newtonsoft.Json"/>
    <PackageReference Include="Serilog"/>
    <PackageReference Include="System.Linq.Dynamic.Core"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Heyer.BuildingBlocks.Application\Heyer.BuildingBlocks.Application.csproj"/>
    <ProjectReference Include="..\Heyer.BuildingBlocks.Domain\Heyer.BuildingBlocks.Domain.csproj"/>
    <ProjectReference Include="..\Heyer.BuildingBlocks.Json\Heyer.BuildingBlocks.Json.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Heyer.BuildingBlocks.Infrastructure.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
